name = "ConwaysGameOfLife"
uuid = "1ae2219f-e16f-43af-afe3-c83b206d5181"
authors = ["TheSunSan <valentino.bergamotto@gmx.net>"]
version = "0.1.0"

[deps]
Documenter = "e30172f5-a6a5-5a46-863b-614d45cd2de4"
GLMakie = "e9467ef8-e4e7-5192-8a1a-b1aee30e663a"
